apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvnproj-deployment
  labels:
    app: mvnproj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mvnproj
  template:
    metadata:
      labels:
        app: mvnproj
    spec:
      containers:
      - name: mvnproj-container
        image: vedhshetty/myapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
