apiVersion: v1
kind: Service
metadata:
  name: mvnproj-service
spec:
  selector:
    app.kubernetes.io/name: mvnproj
  ports:
    - protocol: TCP
      port: 87
      targetPort: 8080
  type: NodePort